---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)

Title <- "Who Cares About Crackdowns? Exploring the Role of Trust in Individual Philanthropy"
Authors <- "Suparna Chaudhry, Marc Dotson, and Andrew Heiss"
Year <- "2020"
```

# `r Title`

[Suparna Chaudhry](http://www.suparnachaudhry.com/) • Department of International Affairs • Christopher Newport University  
[Marc Dotson](https://marriottschool.byu.edu/directory/details?id=50683) • Marriott School of Business • Brigham Young University  
[Andrew Heiss](https://www.andrewheiss.com/) • Andrew Young School of Policy Studies • Georgia State University

---

## Abstract

Over the past two decades, international non-governmental organizations (INGOs) have faced increasing legal scrutiny and repression abroad. As a result, official aid to INGOs in repressive countries has reduced. NGOs thus need access to a diverse array of funds and may need to increase fundraising from private donors. Which demographic and experiential factors influence the decision of individuals to donate to legally besieged NGOs? We investigate this question using a market simulation based on a nationally representative conjoint experiment conducted on individuals with a history of charitable giving. We find that trust in political institutions and charities is enormously influential in shaping donor preferences. Donor profiles with high levels of social trust are likely to donate to human rights INGOs with friendly relationships with host governments, and that support hold steady if INGOs face criticism or crackdown. In contrast, donor profiles with lower levels of social trust prefer to donate to organizations that do not face criticism or crackdown abroad. Our findings have practical implications for INGOs that aim to raise funds from the general public amid closing civic space.

---

This repository contains the data and code for our paper. Our pre-print is online here:

> `r Authors`. (`r Year`). *`r Title`*. Accessed `r format(Sys.time(), '%B %e, %Y')`. Online at <dx.doi.org>


## How to cite

Please cite this compendium as:

> `r Authors`. (`r format(Sys.Date(), "%Y")`). *Compendium of R code and data for `r Title`*. Accessed `r format(Sys.time(), '%B %e, %Y')`. Online at <dx.doi.org>


## How to download and replicate

You can either [download the compendium as a ZIP file](/archive/master.zip) or use GitHub to clone or fork the compendium repository (see the green "Clone or download" button at the top of the GitHub page).

TODO: More instructions


## Data

This project includes the following data files:

TODO: List of data


## Licenses

**Text and figures:** All prose and images are licensed under Creative Commons ([CC-BY-4.0](http://creativecommons.org/licenses/by/4.0/))

**Code:** All code is dual-licensed under the [MIT License](LICENSE.md)


## Contributions

We welcome contributions from everyone. Before you get started, please see our [contributor guidelines](CONTRIBUTING.md). Please note that this project is released with a [Contributor Code of Conduct](CONDUCT.md). By participating in this project you agree to abide by its terms.
